### ISSUE TITLE
[EPIC] Machine-drivers integration

### ISSUE THREAD

**Issue by LalatenduMohanty** [code-ready/crc#12]
### Stage 1
  * [x] modify forked machine library #51 
  * Modify forked KVM driver
     * [x] modify disk image use #49
     * [x] modify network use #50 
  * modify forked VirtualBox driver
     * [x] modify disk image use #52

**Comment by gbraad** [comment]
Ref: https://github.com/code-ready/crc/issues/34
