### ISSUE TITLE
[Epic] introduction of presets to define the 'mode' and 'resource usage'/compatibility of the cluster

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2167]
With presets it is possible to set a mode in which the CRC VM will run and therefore define the expected resource usage and compatibility with OpenShift.

  * [ ] We need to define what the presets are #2166

**Comment by drpaneas** [comment]
Great feature! Thanks for looking into that direction.

**Comment by guillaumerose** [comment]
(breakdown session summary)

3 options:
- Podman only
- crc as it is right now
- crc with monitoring enabled

For a first implementation, we won't support moving from Podman level to OpenShift without restarting the VM, etc.

Issues to be created:
- [ ] Add configuration option for the preset in ~/.crc/crc.json 
- [ ] Introduce an interface that all presets will implement. It will be use in machine.Start() and change the behaviour after the VM is created/started.
- [ ] Each preset will have his own `crc start` output message.
- [ ] Change the behavior of machine.Status() based on the preset (extend the interface - use this to refine CrcStatus field to be not only the VM libmachine status, use only the preset status) - this needs to be expanded
- [ ] Add an e2e test
- [ ] In trays, add a slider which allow the user to select the preset. Duplicate the information for now (preset names, descriptions, ...)

Comments:
Some preflights might not be needed for certain mode.
