### ISSUE TITLE
[Epic] Support OpenShift 4.8 

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2458]
OpenShift 4.8 will be released in July. crc needs to be ready to ship this version as soon as possible.
All the improvements made by the Edge team allow us to turn on the machine-config operator.

* [x] Turn on the MCO by default
* [x] Prepare a pre-release of crc with OpenShift 4.8-rc.0 to get feedback
* [x] Fix bundle generation
* [x] Keep an eye for https://bugzilla.redhat.com/show_bug.cgi?id=1975078

**Comment by guillaumerose** [comment]
Will ship in 1.30.0
