### ISSUE TITLE
[Epic] User can run crc on Apple silicon (M1/M2)

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#2480]
@gbraad here:

Our first target is to enable this for the Podman bundle.

Support to generate SNC bundles has been merged; https://github.com/code-ready/snc/pull/454, though as mentioned in https://github.com/code-ready/snc/pull/454#issuecomment-904835166 more work is needed in regards to the driver.

  * #1850
  * https://github.com/code-ready/crc/issues/2881#issuecomment-992269314

---

Currently, crc  is not running on Apple M1. The goal is to fully support this platform, like Apple and amd64 arch.

**Comment by denismaggior8** [comment]
Any update on this?

**Comment by guillaumerose** [comment]
crc currently uses hyperkit as the hypervisor. This is not possible anymore with M1. The easiest thing to do is to use qemu.

First step is to adapt https://github.com/code-ready/machine-driver-hyperkit/ for qemu.
We also need to update https://github.com/containers/gvisor-tap-vsock to the latest version.

**Comment by gbraad** [comment]
We are currently working on a new driver for the Virtualization Framework that is part of Catalina and Big Sur.
More details around this will follow.

**Comment by gbraad** [comment]
Support to generate SNC bundles has been merged; https://github.com/code-ready/snc/pull/454

**Comment by cfergeau** [comment]
I made some progress on issue #1850, I can run crc using virtualization.framework for the VM. However, this is currently only working on x86_64, I haven't been able yet to start a VM on a M1 machine :-/

**Comment by gbraad** [comment]
To time-line is to offer

* [x] fcos image for podman
* [ ] run this on arm/m1
* [ ] add microshift
* [ ] test microshift on arm/m1

**Comment by praveenkumar** [comment]
I created the fcos bundle on `aarch64` and tried on m1 using vfkit (work which @cfergeau did) and able to start the podman bundle. 
https://github.com/code-ready/snc/issues/502

**Comment by gbraad** [comment]
A dev preview for M1 is available: https://github.com/code-ready/crc/discussions/2988 Things might or might not work, so be sure to add. Comm ets to the discussion. Especially the UI is still changing.

**Comment by mwitteveen** [comment]
Same as [raisingdibar](https://github.com/raisingdibar), I'm developing an application for the Dutch government and just bought a new Macbook m1 max to develop this on.

Is there any time indication for when the M1 Openshift release for CRC is expected?

At this moment, I am walking around with a separate Linux laptop just to run the cluster on.....

**Comment by cfergeau** [comment]
> Is there any time indication for when the M1 Openshift release for CRC is expected?

Unfortunately this is not as straightforward as we'd like, as there are low-level incompatibilities between RHEL and the M1 Hardware Virtualization, see https://access.redhat.com/solutions/6545411 or https://access.redhat.com/discussions/5966451

> RHEL 7 or 8 for aarch64 don't run virtualized in a Mac with Apple M1 processor.

**Comment by mwitteveen** [comment]
> > Is there any time indication for when the M1 Openshift release for CRC is expected?
> 
> Unfortunately this is not as straightforward as we'd like, as there are low-level incompatibilities between RHEL and the M1 Hardware Virtualization, see https://access.redhat.com/solutions/6545411 or https://access.redhat.com/discussions/5966451
> 
> > RHEL 7 or 8 for aarch64 don't run virtualized in a Mac with Apple M1 processor.

But it looks like RHEL 9 is running on M1's. Is this going to solve the problem?

**Comment by cfergeau** [comment]
> But it looks like RHEL 9 is running on M1's. Is this going to solve the problem?

Yes, this should help, but this means OpenShift on RHEL9 is required before we can ship OpenShift on M1

**Comment by jamesdhope** [comment]
Is there an update on this please?

**Comment by cfergeau** [comment]
The PR to switch from hyperkit to virtualization framework on x86_64 macs is opened at https://github.com/code-ready/crc/pull/3035 and hopefully will get merged for the next release.

Once this is in, a few more commits are needed for m1 support in crc https://github.com/cfergeau/crc/commits/macos-vf and a few additional changes in our bundle generation code https://github.com/code-ready/snc/pull/503 

This will initially only support running podman containers, and not openshift clusters.

**Comment by rasheedamir** [comment]
@cfergeau so, when do you think support for openshift clusters will be available?

**Comment by cfergeau** [comment]
> @cfergeau so, when do you think support for openshift clusters will be available?

This still depends on https://github.com/code-ready/crc/issues/2480#issuecomment-1047901005 , I'm not sure what the anticipated schedule is for this.

**Comment by marcelomrwin** [comment]
I understand the complexity but I confess that this incompatibility has a very negative effect on developers. Especially those who got the M1 to gain more productivity. In the absence of a local container, I recommend using Openshift Sandbox https://developers.redhat.com/developer-sandbox/get-started. However for local tests we have minikube or other kubernetes distributions that already support mac m1. 
My opinion is that once we get used to minikube and other local options we don't want to go back to the local crc when it becomes available. And right now, we don't even know if it's going to be supported or when it's going to be supported.

**Comment by gbraad** [comment]
> once we get used to minikube

At the moment e are offering a Podman VM that will be used to run Microshift on M1. this has already been tested but not released yet.

**Comment by gbraad** [comment]
Missing:

  * test infrastructure
  * end to end install (tray has been partially modified to handle Podman-only)
  * OpenShift support
    * build infrastructure for images
    * ... TBD

**Comment by gbraad** [comment]
Please close this one and create a follow-up with the new targets and schedule.

/cc: @code-ready/crc-team @praveenkumar
