### ISSUE TITLE
[QE][Meta] Dev preview overview

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#2970]
This is an aggregation of different issues found during testing the tech preview version [1.99.0](https://github.com/code-ready/crc/releases/tag/dev-1.99.0) and [1.99.1](https://github.com/code-ready/crc/releases/tag/dev-1.99.1).  And latest internal builds based on `crc dev branch` and `tray-electron master branch`

We can consider these issues as essential (required to be solved) before ack on release as GA.

### UX
- [x] https://github.com/code-ready/tray-electron/issues/81
- [x] https://github.com/code-ready/tray-electron/issues/53
- [x] https://github.com/code-ready/tray-electron/issues/82
- [x] https://github.com/code-ready/tray-electron/issues/115
- [x] https://github.com/code-ready/tray-electron/issues/101
- [x] https://github.com/code-ready/tray-electron/issues/113
- [x] https://github.com/code-ready/tray-electron/issues/122

### Functional
- [x] https://github.com/code-ready/tray-electron/issues/83
- [x] https://github.com/code-ready/crc/issues/2947 
- [x] https://github.com/code-ready/crc/issues/2948
- [x] https://github.com/code-ready/tray-electron/issues/70
- [x] https://github.com/code-ready/tray-electron/issues/72
- [x] https://github.com/code-ready/tray-electron/issues/71
- [ ] https://github.com/code-ready/tray-electron/issues/99 
- [x] https://github.com/code-ready/tray-electron/issues/100  
- [x] https://github.com/code-ready/tray-electron/issues/125
- [x] https://github.com/code-ready/tray-electron/issues/108
- [x] https://github.com/code-ready/tray-electron/issues/109
- [x] #2972

#### Pull secret management
- [x] https://github.com/code-ready/tray-electron/issues/61
- [x] https://github.com/code-ready/tray-electron/issues/75
- [ ] https://github.com/code-ready/crc/issues/2950  
- [x] https://github.com/code-ready/tray-electron/issues/98
- [ ] https://github.com/code-ready/tray-electron/issues/106

#### Presets management
- [x] https://github.com/code-ready/tray-electron/issues/63 
- [ ] https://github.com/code-ready/crc/issues/2942 (**Out of scope for initial merge**)
- [ ] https://github.com/code-ready/tray-electron/issues/120
- [x] https://github.com/code-ready/tray-electron/issues/121

**Comment by gbraad** [comment]
> before ack on merging the changes to master.

Merging will happen regardless of acknowledge

**Comment by gbraad** [comment]
Will need to sync up with you guys as changes are made
