### ISSUE TITLE
[META] Track `Running setup` screen

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#3014]
* [ ] https://github.com/code-ready/tray-electron/pull/146
* [ ] https://github.com/code-ready/crc/issues/2935
* [ ] https://github.com/code-ready/crc/pull/2984
* [ ] https://github.com/code-ready/tray-electron/issues/114

**Comment by praveenkumar** [comment]
@gbraad how https://github.com/code-ready/snc/pull/503 is part of this setup?
