### ISSUE TITLE
[Epic] User can click to perform all usual command line actions (system trays)

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#723]
As planned, the Goal is to have a systemtray for crc. It'll make repetitive actions like start/stop possible with a few clicks. This would be useful for developers who tend to stay on the IDE . They'd perform all interactions with the cluster using IDE provided plugins. In that scenario having a tray to manage the crc cluster would fit in without much friction.

We'd need a server component (crc daemon) to perform the actions on behalf of  the  GUI component.

- [x] system process; daemon/network service #796 
- [x] allow changing configuration through the daemon #1246 

systray
- [x] macOS #794 
- [x] Windows #795
   - [x] https://github.com/code-ready/tray-windows/issues/5

**Comment by gbraad** [comment]
@anjannath ping

**Comment by anjannath** [comment]
@gbraad macOS system tray can be moved out of experimental, remaining thing for the windows system tray to be out of experimental is

 - https://github.com/code-ready/tray-windows/issues/5

**Comment by gbraad** [comment]
Will happen at the same time..

**Comment by gbraad** [comment]
This issue can be closed as the epic has been resolved. Everything now are follow-up issues
